const EXCHANGE_TYPES = ["SIZE", "QUALITY", "DEFECTIVE", "OTHER"];

const EXCHANGE_STATUSES = [
  "REQUESTED",
  "PAYMENT_PENDING",
  "APPROVED",
  "PICKUP_SCHEDULED",
  "IN_TRANSIT",
  "COMPLETED",
  "REJECTED",
  "CANCELLED",
];

const ACTIVE_EXCHANGE_STATUSES = [
  "REQUESTED",
  "PAYMENT_PENDING",
  "APPROVED",
  "PICKUP_SCHEDULED",
  "IN_TRANSIT",
];

const TERMINAL_EXCHANGE_STATUSES = ["COMPLETED", "REJECTED", "CANCELLED"];

const EXCHANGE_WINDOW_DAYS = 7;

const PAYMENT_STATUSES = ["NOT_REQUIRED", "PENDING", "PAID", "FAILED"];

module.exports = {
  EXCHANGE_TYPES,
  EXCHANGE_STATUSES,
  ACTIVE_EXCHANGE_STATUSES,
  TERMINAL_EXCHANGE_STATUSES,
  EXCHANGE_WINDOW_DAYS,
  PAYMENT_STATUSES,
};
